### ISSUE TITLE
Importing the US Life cycle inventory into Brightway2 and running on Activity Browser

### ISSUE THREAD

**Issue by tapajyoti-ghosh** [Depart-de-Sentier/brightcon-2024-material#11]
# US life cycle inventory
### The [USLCI database](https://www.lcacommons.gov/lca-collaboration/search/page=1&group=National_Renewable_Energy_Laboratory) provides individual gate-to-gate, cradle-to-gate, and cradle-to-grave accounting of the energy and material flows into and out of the environment that are associated with producing a material, component, or assembly in the U.S.

The goals of the USLCI Database project are to:

- Maintain data quality and transparency
- Cover commonly used materials, products, and processes in the U.S. with up-to-date, critically reviewed life cycle inventory data
- Support the expanded use of life cycle assessment as an environmental decision-making tool
- Maintain compatibility with international life cycle inventory databases
- Provide exceptional data accessibility
- Be fully and sustainably supported
- Support U.S. industry competitiveness.

**Federal Life Cycle Assessment Commons**
The Federal LCA Commons (FLCAC) is an interagency community of practice for life cycle assessment research methods. The FLCAC collaborates to share expertise and methods to move toward common federal data modeling conventions and make federal data sets freely available through a web-based data repository.

**Links**
https://github.com/FLCAC-admin/uslci-content/blob/dev/docs/release_info/release-downloads.md
https://www.lcacommons.gov/lca-collaboration/
https://github.com/FLCAC-admin/uslci-content/tree/dev?tab=readme-ov-file

### Challenges
- USLCI is based on the olca 1.10.3 format and currently uses the olca 2.0.0 format
- Processes have multiple products
- Large number of dummy flows
- Allocation issues
- UUID errors
- Biosphere is different than Brightway2 biosphere
- Only 2 CF methods available 
- Only compatible with OpenLCA Green Delta. 

### Tasks 

- [x] Import USLCI FY23q2 olca v1.10.3 
- [x] Correct allocation issues
- [x] Corrected UUID errors
- [x] Correct dummy flows
- [x] Report dummy flows, missing providers, incorrect providers to USLCI maintainer ( Eastern Research Group)
- [x] Allocation of byproducts by separating activities
- [x] Correct input,output UUIDS, process UUIDS
- [x] Match activities and flow attributes with ecoinvent
- [x] Square technosphere matrix
- [x] LCA and LCIA calculations
- [x] Import in Activity Browser and perform LCA

**Comment by tjlca** [comment]
## Current status

Environment and packages. Kindly ask for the updated bw2io 0.9 dev 27 for importing USLCI.

```
bw-migrations                 0.2
bw-processing                 0.9
bw2calc                       2.0.dev16
bw2data                       4.0.dev33
bw2io                         0.9.dev27**
bw2parameters                 1.1.0
```


Code snippets: 

<img width="879" alt="image" src="https://github.com/user-attachments/assets/4e3be2b7-5edb-4331-b242-4b3426d0723b">

<img width="585" alt="image" src="https://github.com/user-attachments/assets/1fdb7b6c-183d-40da-856f-a0b567183be5">


**Performing LCA:**
Electricity, at eGrid, RMPA, 2010 Northern America
0.9381940660065312

**Processes - 863**
<img width="732" alt="image" src="https://github.com/user-attachments/assets/7b31fe5b-8db2-421b-8820-6f7069dda183">

Special thanks to the Activity Browser Team (Marin Visscher, Marc Meide) for helping import into Activity Browser. 
Activity Browser challenges - The database was processed inside Brightway2.5 libraries resulting in zip files for biosphere methods rather than numpy arrays. We had to reprocess them with Brightway2 to make them compatible. 
<img width="1668" alt="image" src="https://github.com/user-attachments/assets/cb80b518-3e82-430f-b4bb-0e5923711939">

**Comment by tjlca** [comment]
Files available - https://github.com/tjlca/Brightway2-USLCI/tree/test_dev
